### ISSUE TITLE
Install error with tensorflow-macos

### ISSUE THREAD

**Issue by guikool** [matchms/ms2deepscore#104]
Dear developer
thank you for your amazing suite of matchms and other packages, its really helpful
Still, under mac M, I'm unable to install ms2deepscore due to a conflict with tensorflow although tensorflow-macos 2.9.2 is installed in my matchms environment:

ERROR: Cannot install ms2deepscore==0.1.0, ms2deepscore==0.1.1, ms2deepscore==0.1.2, ms2deepscore==0.1.3, ms2deepscore==0.2.0, ms2deepscore==0.2.1, ms2deepscore==0.2.2 and ms2deepscore==0.2.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    ms2deepscore 0.2.3 depends on tensorflow

Did you know this issue or is it from my config (Mac M1, miniforge3, python 3.9)
Thanks
G.

**Comment by svenvanderburg** [comment]
@guikool are you sure you installed `tensorflow-macos` in your virtual environment? This error indeed comes up on mac M1, and can be solved by installing tensorflow through `pip install tensorflow-macos`. I will document that better.

Can you post the output of `pip freeze | grep tensorflow` to double check if you have tensorflow installed.

**Comment by svenvanderburg** [comment]
I have documented instructions for installation on macos with M1 chip in https://github.com/matchms/ms2deepscore/pull/106

**Comment by guikool** [comment]
Hello, thanks for the reply,
After intensive browsing, I finally found a tutorial here:
[https://makeoptim.com/en/deep-learning/tensorflow-metal](url)
and solve the numpy error

Now, here is the read backs of `pip freeze | grep tensorflow`
tensorflow-estimator==2.9.0
tensorflow-macos==2.9.2
tensorflow-metal==0.5.1

A quick test show that my tensorflow environment is working (python 3.9.5)
but same conflict issue after `pip install ms2deepscore  `

**Comment by guikool** [comment]
I finally manage to install matchms, speed2vec and ms2deepscore in the same environment using the anaconda M1 version distribution. `tensorflow-macos` doesn't work but using `tensorflow` is ok to perform the installation of all packages.
Still, surprisingly RDkit is not recognized and provided an error during "metadata processing". Another issue comes from ms2query install failure with h5py (I'll open an issue).
Thanks for your great jobs on these really interesting package suits.
Best regards
G.

**Comment by svenvanderburg** [comment]
Great that you figured it out!
