### ISSUE TITLE
error: network from MS2deep scores

### ISSUE THREAD

**Issue by guikool** [matchms/ms2deepscore#105]
Dear developers
I've followed the MS2deepscore short tuto to create a network from the GNPS-NIH-NATURALPRODUCTSLIBRARY.mgf to compare results with the classical modified cosine.
Still, in both cases, I've obtained an error during network creation (all previous command in the script work well)
ValueError: None cannot be a node

Here is the drawbacks of 

`ms_network.create_network(scores)`
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [23], line 1
----> 1 ms_network.create_network(scores)

File d:\Docs\Logiciels\Anaconda3\envs\ms2deepscore\lib\site-packages\matchms\networking\SimilarityNetwork.py:123, in SimilarityNetwork.create_network(self, scores)
    121 # Initialize network graph, add nodes
    122 msnet = nx.Graph()
--> 123 msnet.add_nodes_from(unique_ids)
    125 # Collect location and score of highest scoring candidates for queries and references
    126 similars_idx, similars_scores = get_top_hits(scores, identifier_key=self.identifier_key,
    127                                              top_n=self.top_n,
    128                                              search_by="queries",
    129                                              ignore_diagonal=True)

File d:\Docs\Logiciels\Anaconda3\envs\ms2deepscore\lib\site-packages\networkx\classes\graph.py:622, in Graph.add_nodes_from(self, nodes_for_adding, **attr)
    620 if newnode:
    621     if n is None:
--> 622         raise ValueError("None cannot be a node")
    623     self._adj[n] = self.adjlist_inner_dict_factory()
    624     self._node[n] = self.node_attr_dict_factory()

ValueError: None cannot be a node

**Comment by svenvanderburg** [comment]
@guikool it seems like you are you referring to [this tutorial](https://blog.esciencecenter.nl/build-a-mass-spectrometry-analysis-pipeline-in-python-using-matchms-part-iii-molecular-91891248ee34)? Is that correct?

If that is the case, this is probably an issue with the `matchms` library, you can raise an issue [here](https://github.com/matchms/matchms/issues).

**Comment by guikool** [comment]
That's correct, I'll post the issue to matchms

**Comment by florian-huber** [comment]
Thanks @svenvanderburg . It is now an issue in matchms. So this can be closed.
