### ISSUE TITLE
API discussions

### ISSUE THREAD

**Issue by florian-huber** [matchms/ms2deepscore#12]
Currently my vague idea of the API would look like this:
```python
from matchms import load_from_json
from ms2deepscore import SpectrumBinner
from ms2deepscore import DataGeneratorAllSpectrums

# import & process training data
spectrums = load_from_json(....)
spectrums = [process(s) for s in spectrums]

# define binning conditions and process spectrums
spectrums_binned = SpectrumBinner(number_of_bins=10000, mz_min=10.0, mz_max=1000.0,
                                  peak_scaling=0.5, allowed_missing_percentage=10.0)
spectrums_binned.collect_binned_spectrums(spectrums)


# train a model
train_generator = DataGeneratorAllSpectrums(...)
val_generator = DataGeneratorAllSpectrums(...)
...

# import & process query data
spectrums_query = load_from_json(....)
spectrums_query = [process(s) for s in spectrums_query]
spectrums_query_binned = spectrums_binned.create_binned_spectrums(spectrums_query)

# function to calculate similarity between two arbitraty spectra
ms2deepscore.calculate_scores(spectrums_query_binned[0], spectrums_query_binned[1]) 

# function to do library searches
library_object = library_class(spectrums_binned, model)
library_class.derive_embeddings()  # calculate and store embeddings to have them pre-calculated for all following jobs
similarities = library_class.compute_similarities(spectrums_query_binned)
```

**Comment by florian-huber** [comment]
One thing that will be important to keep is the distinction between `training data` and all other data that is used later.
This is mostly to keep track of the `vocabulary` which will reveal if users input spectra with peaks that were not part of the training data. I am not sure how relevant this will be in practice, it will depend a lot on the amount of training data and the number of bins, but if feels like a good security check to me.
It might be cleaner, API-wise, to implement it into a model class tough.

**Comment by svenvanderburg** [comment]
### Some suggestions:
Use sklearn fit/transform API:
```python
# define binning conditions and process spectrums
spectrum_binner = SpectrumBinner(number_of_bins=10000, mz_min=10.0, mz_max=1000.0,
                                 peak_scaling=0.5, allowed_missing_percentage=10.0)
binned_spectrums = binner.fit_transform(spectrums)
```

 * Pass `spectrum_binner` to class 
 * calculate embeddings upon init (what else are you gonna use this class for?)
 * Rename things
 * Return list of `SpectrumSearchResult` objects.
```python
# function to do library searches
spectrum_search = SpectrumSearch(spectrums_binned, model, spectrum_binner) 
# input_spectrum is of type Spectrum and is binned using spectrum_binner
ranked_spectrums = spectrum_search.nearest_neighbours(input_spectrum)
print(ranked_spectrums[0].similarity_score, ranked_spectrums[0].inchi_key)
```

**Comment by svenvanderburg** [comment]
> One thing that will be important to keep is the distinction between `training data` and all other data that is used later.
> This is mostly to keep track of the `vocabulary` which will reveal if users input spectra with peaks that were not part of the training data. I am not sure how relevant this will be in practice, it will depend a lot on the amount of training data and the number of bins, but if feels like a good security check to me.
> It might be cleaner, API-wise, to implement it into a model class tough.

With the example in the description the `SpectrumBinnner` is fitted on **all** data right? Not just the **training** data? So there is a distinction between the data used for training + validating and inference data.

**Comment by florian-huber** [comment]
Yes @svenvanderburg that's correct. I felt that training + validation data could count as being "seen" in one way or another.
But it could also be restricted to bins being in the training set only, what do you think?

**Comment by florian-huber** [comment]
Sketching again:
- `SpectrumBinned` contains: binned peaks (dict, or sparse array), inchikey (can be None), minimal binning metadata (what bins?)
- `SpectrumBinner` contains: methods for binning matchms style `Spectrum`
- `DataGenerator`
- `DeepScoreModel`
```python

```

**Comment by svenvanderburg** [comment]
> Yes @svenvanderburg that's correct. I felt that training + validation data could count as being "seen" in one way or another.
> But it could also be restricted to bins being in the training set only, what do you think?

As discussed. We thought it is better to 'fit' the SpectrumBinner on the training data only. Because otherwise there might be bins in the vocabulary that are not 'seen' during training.

**Comment by florian-huber** [comment]
I think this is outdated. For further API discussion we should start another issue.
