### ISSUE TITLE
Some ideas for nearest neighbour search

### ISSUE THREAD

**Issue by svenvanderburg** [matchms/ms2deepscore#13]
I did some nearest neighbour search before in python, and have good experience with:
* https://github.com/spotify/annoy
* Good old [scipy.spatial.distance](https://docs.scipy.org/doc/scipy/reference/spatial.distance.html) if you can live with a slow brute-force solution, in a project I did we first had a candidate selection step to reduce the search space and than used `scipy` for exact searching.

For visualization of embeddings I highly recommend:
* https://projector.tensorflow.org/

**Comment by florian-huber** [comment]
See also https://github.com/iomega/ms2query/issues/46
