### ISSUE TITLE
Integrate DataGeneratorCherryPicked with DataGeneratorBase

### ISSUE THREAD

**Issue by niekdejonge** [matchms/ms2deepscore#159]
DataGeneratorCherrypicked uses DataGeneratorBase but does not initialize the DataGeneratorBase, while it is the super class.

We use multiple methods from DataGeneratorBase, but the super __init__ can not be run, since DataGeneratorBase uses reference_scores_df while DataGeneratorCherrypicked uses SelectedCompoundPairs.

Two options:
- Update DataGeneratorAllSpectrums and DataGeneratorAllInchikeys to use SelectedCompoundPairs as well
- Remove DataGeneratorAllspectrums and DataGeneratorAllinchikeys, since we want to use DataGeneratorCherrypicked in the future.

**Comment by florian-huber** [comment]
Outdated with #168
