### ISSUE TITLE
Update MS2DeepScore plus MC version for scoring

### ISSUE THREAD

**Issue by florian-huber** [matchms/ms2deepscore#171]
- move the actual scoring functions from the keras model to pytorch.

**Comment by niekdejonge** [comment]
Solved with #169 
@florian-huber Not sure what you meant with MC version, so feel free to reopen if it is not yet solved.

**Comment by florian-huber** [comment]
@niekdejonge with MC I meant the MonteCarlo version --> `MS2DeepScoreMonteCarlo`.
