### ISSUE TITLE
How to handel full network vs. "encoder" part?

### ISSUE THREAD

**Issue by florian-huber** [matchms/ms2deepscore#20]
The Siamese network mostly consists of an "encoder" by which I mean a dense network that reduced the input to a few-hundred dimensional embedding. The last step then is a cosine similarity calculation between two such embeddings (generated from two different inputs). 

For the inference (or: the actual application), however, we later only need the encoder part. That means we only want a network that takes a single binned_spectrum input and returns a single embedding as output. The actual scoring will later be done by performance optimized implementations based on the returned embeddings. 

How do we handle this?
Should the `SiameseModel` also contain the encoder separately (wouldn't that be wasting memory?) ?
Or should be create a separate object from an already trained siamese network?

**Comment by florian-huber** [comment]
Maybe that's already taken care of by having `.base` and `.model` in PR #16 ?

**Comment by svenvanderburg** [comment]
> I think this is now already taken care of by having `.base` and `.model` in PR #16 !

Agree!

**Comment by florian-huber** [comment]
Nice, solved :)
