### ISSUE TITLE
Path to pre-trained model in README

### ISSUE THREAD

**Issue by roman-bushuiev** [matchms/ms2deepscore#225]
Hi! I have a question regarding the "Getting Started" section of the README. It seems that the path to the pre-trained model refers to the old TensorFlow weights, which are not available on Zenodo. Should `MS2DeepScore_allGNPSpositive_10k_500_500_200.hdf5` be replaced with `ms2deepscore_model.pt`? Thank you!

https://github.com/matchms/ms2deepscore/blob/212bbc032e84245f345373cb2b5521587b4f00e0/README.md?plain=1#L87

**Comment by niekdejonge** [comment]
Hi Roman, yes, thanks. That was outdated. 
To be clear, the load_model function just loads a local model file, no downloading is included, this has to be done manually from Zenodo.

**Comment by roman-bushuiev** [comment]
Ok, thank you!
