### ISSUE TITLE
Consider adding SpectrumBinner to SiameseModel

### ISSUE THREAD

**Issue by florian-huber** [matchms/ms2deepscore#23]
This came up when implementing a first full workflow and was briefly discussed in #15.
For a cleaner start, let's discuss further in this issue instead.

Since PR #16 we have `SiameseModel` which contains:
- `.model` --> the actual Siamese network (keras `Model()`)
- `.base` --> the "encoder" part of the network (keras `Model()`)
- methods to mimic the keras API: `.compile()`, `.fit()`, `.summary()` ...

My suggestion would be to also add `.spectrum_binner()` so that the binning procedure and the known binned peaks stay linked to the model. We could then add methods like:
- `.save()`: Save the `SiameseModel` (containing both keras model and SpectrumBinner), e.g. using `pickle`.
- `.load()`

**Comment by svenvanderburg** [comment]
I agree we should wrap the spectrum binner in **a** model class. We have to decide at what level we want to include it. There's 2 options:
1. In the low-level `SiameseModel` class (like @florian-huber suggests above)
2. In the high-level `Ms2DeepScore` class (see #17), that would wrap instances of `DataLoader`, `SpectrumBinner`, `SiameseModel`. Basically wrapping the whole pipeline from spectrum to similarity score, including training in a user-friendly API.

I have a slight preference for 2 (mostly because that feels more intuitive), but 1 also makes sense.

**Comment by florian-huber** [comment]
After a offline discussion with @svenvanderburg I think we decided the following (otherwise please correct):
- Though (2) from the comment above would be a good solution for `MS2DeepScore` on its own, we should go for (1) to stay closer to the `matchms` API. Because in that setting, loading a model or adding methods such as the binner would be unexpected for the users.
- the `Model` class should hence get the `SpectrumBinner`, e.g. `.spectrum_binner()` method?
- the `Model` class should get importing and exporting methods --> #34

**Comment by svenvanderburg** [comment]
> the Model class should hence get the SpectrumBinner, e.g. .spectrum_binner() method?
I think it should just get a `.spectrum_binner` attribute

**Comment by florian-huber** [comment]
Probably I am only confusing terminology here.
I was thinking of adding something like the following to the `SiameseModel` class __init__:
```python
def __init__(self, ..., spectrum_binner): 
    self.spectrum_binner = spectrum_binner
```
Where `spectrum_binner` should be the one used for the model training. Is that also what you meant?

**Comment by svenvanderburg** [comment]
Yes, that's an attribute. A method would be:

```python
class SiameseModel:
    def spectrum_binner():
         ...
```

**Comment by florian-huber** [comment]
I am currently adding this in PR #35

**Comment by florian-huber** [comment]
Done in #36!
