### ISSUE TITLE
DataGeneratorAllSpectrums pair selection mechanism leaks

### ISSUE THREAD

**Issue by svenvanderburg** [matchms/ms2deepscore#24]
For `DataGeneratorAllSpectrums` the 'selection' of the data is based on spectrums (i.e. user passes a list of spectrum_ids to generate data from). As a user I would expect that for each of the spectrum pairs that are generated, both spectrums are in this list that I supplied (because I only want for a limited set of spectrums to be in my training vs test data for example). 

However, only the 'first' spectrum in a pair is in this list of spectrum_ids, whereas the 'second' spectrum can be outside of the spectrum_ids list, see `DataGeneratorAllSpectrums.__find_match_in_range`:
https://github.com/matchms/ms2deepscore/blob/0d80b9c0f5b5add334882aa9ab36da714a7a183c/ms2deepscore/data_generators.py#L181-L213

This is bad, because it could mean that training data leaks into test data.

**Comment by svenvanderburg** [comment]
@florian-huber did I miss something here or is this indeed a problem?

**Comment by florian-huber** [comment]
@svenvanderburg I think you are right. Good catch!
I thought I had addressed that somewhere, but it looks like I didn't. So I will take care of this today!
(probably I will simply remove all inchikeys that are not among the selected spectrums and then only pick from the selected spectrums once `inchikey_id2` is chosen)
