### ISSUE TITLE
Model version does not match the version of MS2Deepscore

### ISSUE THREAD

**Issue by Panzenboeck** [matchms/ms2deepscore#245]
Hi! Thank you for your great work.

I have just installed MS2Deepscore and followed the instructions to use a pre-trained model. After downloading the latest model (published on October 7th) from Zenodo, I get the following error message when running the model = load_model("ms2deepscore_model.pt") command: “The model version (2.0.0) does not match the version of MS2Deepscore (2.2.0), consider downloading a new model or changing the MS2Deepscore version”.  

Could you maybe clarify if this is a mistake on my side or if there was a problem with updating to the latest version as described here: (https://github.com/matchms/ms2deepscore/issues/218). I am sorry for the inconvenience.

Thank you,
Lili

**Comment by niekdejonge** [comment]
@Panzenboeck you can savely use this model in MS2Deepscore 2.2.0. 
We added this warning initially to prevent people from using very old MS2Deepscore 1.0 models in MS2Deepscore 2.0, which will break, but we made this warning way too strict. In a future version we will remove this warning. (Actually I thought I already did, but forgot apparently...) Thanks for notifying us.

**Comment by niekdejonge** [comment]
Implemented in #249, so the warning will be removed with next releases.

**Comment by Panzenboeck** [comment]
Thank you for the information and your quick reply!
