### ISSUE TITLE
Take similarity score closest to bin, instead of highest for fallback option of _find_match_in_range

### ISSUE THREAD

**Issue by svenvanderburg** [matchms/ms2deepscore#32]
See:
https://github.com/matchms/ms2deepscore/blob/52b35348dff2160142cc7bb36ca031bf8f4c5479/ms2deepscore/data_generators.py#L208-L212
As a fallback option, we use the highest similarity score, but it makes more sense to use the similarity score closest to the bin.

**Comment by florian-huber** [comment]
This was fixed in #79
