### ISSUE TITLE
review data generator functions

### ISSUE THREAD

**Issue by florian-huber** [matchms/ms2deepscore#6]
I only did superficial cleaning stuff, which means that those classes are not yet in full proper shape. 
It would be good to check if 1) it makes sense what they do (how they select and augment the data) and 2) how the code looks like (--> cleaning, refactoring...?).

https://github.com/matchms/ms2deepscore/blob/main/ms2deepscore/data_generators.py

**Comment by florian-huber** [comment]
@svenvanderburg, let me know if have some time for doing some code review. That here would be a good start I think. (also feel free to push changes etc. if you like).

**Comment by svenvanderburg** [comment]
@florian-huber I made a start here: #7 Let me know if this sort of is what you had in mind.

**Comment by florian-huber** [comment]
Thanks, I now updated and refactored the generators in #8

**Comment by florian-huber** [comment]
Thanks again for the review Sven!
I'll close this issue.
