### ISSUE TITLE
Incorrect epoch estimation in AllInchikeys generator

### ISSUE THREAD

**Issue by florian-huber** [matchms/ms2deepscore#61]
```
return int(self.settings["num_turns"]) * int(np.floor(len(self.reference_scores_df) / self.settings[
            "batch_size"]))
``` 
--> should not be calculated using self.reference_scores_df` but based on actual inchikeys in the training data.

**Comment by svenvanderburg** [comment]
This seems to be correct? I couldn't find how this is an incorrect estimation of the number of batches?
The inchikeys in `reference_score_df` **are** the inchikeys in the training data, see:
https://github.com/matchms/ms2deepscore/blob/d17b7b94502db539def1426c265715095cf13587/ms2deepscore/data_generators.py#L427-L429 
https://github.com/matchms/ms2deepscore/blob/d17b7b94502db539def1426c265715095cf13587/ms2deepscore/data_generators.py#L458-L462
In fact we use `reference_score_df` directly to define `self.indexes`
https://github.com/matchms/ms2deepscore/blob/d17b7b94502db539def1426c265715095cf13587/ms2deepscore/data_generators.py#L464-L466
https://github.com/matchms/ms2deepscore/blob/d17b7b94502db539def1426c265715095cf13587/ms2deepscore/data_generators.py#L438-L448

But maybe I misunderstood the issue, can you be more specific @florian-huber ?

**Comment by svenvanderburg** [comment]
It is indeed correct, @svenvanderburg will add a note.
