### ISSUE TITLE
Manuscript TODO's & priorities

### ISSUE THREAD

**Issue by florian-huber** [matchms/ms2deepscore#62]
This issue is meant to discuss what is still needed/desired for the first manuscript. Here it should mostly be about keeping track of things, for more extensive discussions simply make a new issue and link to it.

- Compare two very different molecular fingerprints (now we use rdkit, daylight, 2048bit, maybe add circular fingerprint?)
- Identify key parameters to explore, e.g. no. of layers, dimension of layers, learning rate... --> #68 
- More closely inspect possible correlations between performance and molecular properties, e.g. parent mass vs. accuracy...

Once key aspect is to decide on the audience/focus.
My idea was to publish MS2DeepScore fast and “lightweight”, by this I mean that I would rather make it into a short, machine-learning focused paper. 
Still, we will obviously need to show its relevance to the mass spec field. For this we can include:
- overall benchmarking (the distributions plot we already have, so how well does it predict Tanimoto)
- some comparison with modified Cosine (matchms implementation) and Spec2Vec.
- have some concrete examples of compounds where it works better/worse ?

**Comment by florian-huber** [comment]
only point missing from the above mentioned bullet points is: 

> have some concrete examples of compounds where it works better/worse ?

**Comment by justinjjvanderhooft** [comment]
that looks to be a pretty daunting one to come up with quickly - perhaps mention in the discussion that it would be interesting to further investigate for which compound classes MS2DeepScore works well, and where we still need alternative methods/complementary approaches/integrated metrics? That kind of covers that point.

**Comment by florian-huber** [comment]
Other ideas that came up for additional discussion or next steps:
- Experiment with binning → “smart” binning based on peak importance (e.g. something like tfidf?).

- Mention that we played around with Distributional Parameter Estimation and this could be experimented with further.

- Often the embeddings have a bit “undesirable” characteristics, e.g. only positive values (relu) and/or huge entries (exploding gradient problem?). Plus they tend to be sparse, which however might not be a real issue, at least not for the cosine similarity layer case→ here we could simply normalize the embedding to max_entry=1.
- dimensionality reduction and rescaling to get desired embeddings for downstream tasks.

**Comment by florian-huber** [comment]
Article is long out now: https://jcheminf.biomedcentral.com/articles/10.1186/s13321-021-00558-4

So I will close this and keep the future/next steps ideas in #102
