### ISSUE TITLE
Evaluation metric

### ISSUE THREAD

**Issue by svenvanderburg** [matchms/ms2deepscore#74]
We need an evaluation metric to evaluate on the testset.

There is 2 challenges:
## 1. The data is heavily left-skewed (i.e. most pairs have low tanimoto scores)
We can calculate all scores and then weigh them based on the y label bin they fall into.

## 2. What is the best evaluation metric?
I would say:
**MSE**: Hard to interpret what it means
**MAE**: Gives less weight to large errors (i.e. median), so pick this if we care about most samples giving reasonable output, tolerating some large errors.
**RMSE**: Gives more weight to large errors (i.e. mean), so pick this if we want the error to be low on each single case.

- [x] add description to the Methods.

**Comment by florian-huber** [comment]
Regarding (2): My feeling is that MSE or RMSE make more sense for most applications I have in mind, e.g. detecting similar compounds. There we really want to avoid too many outliers (=large discrepancies between Tanimoto<->Tanimoto(predicted).). But small differences are generally acceptable.

You would prefer **RMSE** over **MSE**?

**Comment by svenvanderburg** [comment]
We pick RMSE because of above mentioned benefits.
