### ISSUE TITLE
Use balanced subsampling for data generation

### ISSUE THREAD

**Issue by svenvanderburg** [matchms/ms2deepscore#81]
Our current approach of balancing the data during data generation is picking an inchikey, than looking for a pair in a randomly sampled similarity bin, and iteratively widening the bin until a pair is found. It is hard to understand what the data exactly looks like that comes out of this, and it is a bit complex. It suggest instead to use stratified sampling:

On epoch end:
1. We take all inchikey pairs with their similarity label
2. We take a random subsample that is balanced for the similarity labels (I think the term would be: Random majority under-sampling with replacement)
3. We loop over the selected inchikey pairs to generate training examples 
4. We still do spectrum selection and data augmentation on the individual training example level

To me this is more transparent, because it will ensure that the y label is indeed exactly balanced. And it is a bit cleaner.

**Comment by florian-huber** [comment]
This is partly addressed in #145.
Therein a new data generator is introduced (`DataGeneratorCherrypicked`,  naming is up for discussion...). This will pre-select pairs in a way that aims to counteract strong biases in the scores. However, there can still be remaining biases if we have few scores for specific score bins. For such cases we might still want to add things like over-sampling or adjusted weights or more specific loss functions to our routine.
