### ISSUE TITLE
TensorFlow update breaks SiameseModel._construct_from_keras_model()

### ISSUE THREAD

**Issue by dianacarvalho1** [matchms/ms2deepscore#91]
The current TensorFlow version 2.6.0 (released in August 11th) breaks the `SiameseModel._construct_from_keras_model()` method. The assertion `assert isinstance(keras_model, keras.Model)` is not `True` anymore and throws the error `AssertionError: Expected keras model as input.`. 
I would suggest fixing the TensorFlow version to 2.5.0 or even updating the code.

Thank you!

**Comment by florian-huber** [comment]
Thanks @dianacarvalho1 for making this issue!
I will run some quick tests. I prefer updating the code so that it is also compatible with TensorFlow 2.6 and will fix the version if that won't easily work.

**Comment by florian-huber** [comment]
I could fix it for tensorflow 2.6 and will now add tests for 2.4, 2.5 and 2.6

**Comment by florian-huber** [comment]
Fixed with #92 . Will be part of the next release (to be done asap).

**Comment by dianacarvalho1** [comment]
Thank you so much @florian-huber!
